// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FamTracker
{
	public partial class View : NSWindowController
	{
		public View (IntPtr handle) : base (handle)
		{
		}
	}
}
